### ISSUE TITLE
Error: "window is not defined" on v2.0.8

### ISSUE THREAD

**Issue by barbalex** [dweirich/gatsby-plugin-react-leaflet#11]
When building with v2.0.4 this did not happen.
When I update to v2.0.8, then run `yarn build` it does:
```
error Building static HTML failed

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

  228 | }
  229 |
> 230 | var requestFn = window.requestAnimationFrame || getPrefixed('RequestAnimationFrame') || timeoutDefer;
      | ^
  231 | var cancelFn = window.cancelAnimationFrame || getPrefixed('CancelAnimationFrame') ||
  232 |                 getPrefixed('CancelRequestAnimationFrame') || function (id) { window.clearTimeout(id); };
  233 |


  WebpackError: ReferenceError: window is not defined

  - leaflet-src.js:230
    [lib]/[leaflet]/dist/leaflet-src.js:230:1

  - leaflet-src.js:7
    [lib]/[leaflet]/dist/leaflet-src.js:7:62

  - leaflet-src.js:10 Object../node_modules/leaflet/dist/leaflet-src.js
    [lib]/[leaflet]/dist/leaflet-src.js:10:2

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - AttributionControl.js:1 Module../node_modules/react-leaflet/es/AttributionControl.js
    [lib]/[react-leaflet]/es/AttributionControl.js:1:1

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - index.js:1 Module../node_modules/react-leaflet/es/index.js
    [lib]/[react-leaflet]/es/index.js:1:1

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - Kontakt.js:1 Module../src/pages/Kontakt.js
    lib/src/pages/Kontakt.js:1:1

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - sync-requires.js:11 Object../.cache/sync-requires.js
    lib/.cache/sync-requires.js:11:57

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - static-entry.js:9 Module../.cache/static-entry.js
    lib/.cache/static-entry.js:9:22

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1

  - bootstrap:83
    lib/webpack/bootstrap:83:1
```
Looks exactly like https://github.com/dweirich/gatsby-plugin-react-leaflet/issues/8 and https://github.com/dweirich/gatsby-plugin-react-leaflet/issues/9 but happens to me with v2.0.8.

This is my project: https://github.com/barbalex/gs3

**Comment by dweirich** [comment]
Hi @barbalex I've tried a clone of your project with 2.0.8 and didn't run into any build errors. Are you certain you're on 2.0.8?

**Comment by barbalex** [comment]
This is extremely weird. I have done:
- set v2.0.8 in package.json
- `del yarn.lock && rmdir /s node_modules && yarn && yarn build` multiple times
- `del yarn.lock && rmdir /s node_modules && yarn cache clean && yarn && yarn build` (which actually crashed my windows pc the first time with a cache related yarn error occuring on the next try with only the third being successful)

And I still get this error.

I do not understand why the error should occur as I have never installed any version of gatsby-plugin-react-leaflet between 2.0.4 and 2.0.8.

I feel that this is not related to gatsby-plugin-react-leaflet but some edge case of yarn.

**Comment by barbalex** [comment]
Hm. Maybe not a yarn problem:

```
del yarn.lock && rmdir /s node_modules && yarn cache clean
npm i
npm run build
```

=> same error

**Comment by barbalex** [comment]
So I set back to v2.0.4 in package.json, then `yarn && yarn build`: works.

@dweirich  I realize you have tried what you can and can do nothing as you can't replicate this. I am not trying to spam you into action, just noting it all in case others encounter the same issue.

**Comment by barbalex** [comment]
Works an my MacBook with v2.0.8

**Comment by barbalex** [comment]
The error happens exact same on my Windows 10 Notebook.

Is it possible that this happens only on Windows?

**Comment by dweirich** [comment]
I believe that is probably the case. I was testing on a Mac as well. I'll look into this to see if I can find a solution.

**Comment by FraserThompson** [comment]
Just FYI I have the same error after updating to 2.0.8 on Windows 10, so it appears the 2.0.8 update is broken on Windows 10.

**Comment by dweirich** [comment]
The regex I used to null the modules did not take Windows into consideration. I’m out today, but I’ll get this fixed tomorrow.

**Comment by dweirich** [comment]
Sorry for the hold up on this issue. I've gotten very busy in the last few days.

I released a beta version to test on a Windows machine, but didn't have time to debug why the URLs weren't resolving correctly. The initial changes were made to stop from breaking projects that had the word `leaflet` in the project name. It seems like the fixes for that are causing more problems than the original issue, so I'm going to revert the library back to using the methods from 2.0.4.

**Comment by barbalex** [comment]
Thanks a lot for dedicating so much effort to this project!

**Comment by dweirich** [comment]
Ok, I've pushed an update to npm to fix this. Feel free to re-open if anyone is still having issues with it.

**Comment by barbalex** [comment]
Works like a charm
