### ISSUE TITLE
Can't extend react-leaflet components

### ISSUE THREAD

**Issue by r3mi** [dweirich/gatsby-plugin-react-leaflet#15]
Hello,

(refer to issue https://github.com/PaulLeCam/react-leaflet/issues/645 )

I am using `gatsby-plugin-react-leaflet` in my Gastby app (thanks !), and extending some components from `react-leaflet`
```js
class MyGridLayer extends GridLayer {
   ...
}
```
Everything is fine in development mode (`gatsby develop`). However, when I try to build (`gatsby build`), I get:
```
WebpackError: TypeError: Class extends value undefined is not a constructor or null
```
on `GridLayer`.

After investigation, if I remove `react-leaflet`  from the webpack config in https://github.com/dweirich/gatsby-plugin-react-leaflet/blob/master/gatsby-node.js (leaving only `leaflet`), it solves the issue, and the build is fine.

Is there a reason to exclude `react-leaflet` from the SSR build ?

Thanks for your plugin,

**Comment by colbyfayock** [comment]
confirmed was able to run and build with the following only:
```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    const regex = [
      /node_modules\/leaflet/,
      /node_modules\\leaflet/
    ];
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: regex,
            use: loaders.null()
          }
        ]
      }
    })
  }
}
```

**Comment by colbyfayock** [comment]
opened a pull request in the event this change is 👍 
https://github.com/dweirich/gatsby-plugin-react-leaflet/pull/16

**Comment by dweirich** [comment]
Hi @colbyfayock I'll get around to look at this later today. Thanks for the PR!
