### ISSUE TITLE
not working in develop mode?

### ISSUE THREAD

**Issue by smeijer** [dweirich/gatsby-plugin-react-leaflet#17]
Does this plugin only work in `gatsby build` mode? I've followed the steps in the readme, and the `window is not defined` error doesn't show up for `gatsby build` any longer.

Yet, for `gatsby develop`, it still does.

**Comment by dweirich** [comment]
Hi @smeijer, thank you for the pull request. I will look into this and try to get it merged over the weekend.

**Comment by smeijer** [comment]
Awesome! I've applied that same change in my `node_modules` dir, and it has been working great this week.

Thanks for this plugin.
