### ISSUE TITLE
`crossorigin` error message when running in dev mode

### ISSUE THREAD

**Issue by hlouw** [dweirich/gatsby-plugin-react-leaflet#2]
Adding the react-leaflet plugin to my Gatsby project gives the following error when I run `gatsby develop` (but not `gatsby build`):

```
Warning: Invalid DOM property `crossorigin`. Did you mean `crossOrigin`?
    in link
    in head
    in html
    in HTML
```

Not sure what the effect is, the plugin still seems to work, but probably an easy fix.

**Comment by dweirich** [comment]
This has been fixed in the latest push, thanks for bringing it to my attention!
