### ISSUE TITLE
Compatibility with react-leaflet v3

### ISSUE THREAD

**Issue by Vacilando** [dweirich/gatsby-plugin-react-leaflet#20]
Is this plugin compatible with react-leaflet v3?

When using react-leaflet@3.0.5 I get this error from npm list:

npm ERR! peer dep missing: react-leaflet@^2.0.0, required by gatsby-plugin-react-leaflet@2.0.13

**Comment by dweirich** [comment]
Hey @Vacilando thanks for pointing this out. I've just published a new major version to npm that should solve this for you. Let me know if it doesn't work.

**Comment by Vacilando** [comment]
It's fine now, thanks!
