### ISSUE TITLE
Gatsby 3 - feature request

### ISSUE THREAD

**Issue by linoxyn** [dweirich/gatsby-plugin-react-leaflet#21]
A Gatsby 2 website I built for a friend has a Leaflet component which zooms into a very large image of one of his artworks, not a map, it works very well. I have not yet tested this plugin with Gatsby version 3 so I don't know what may or may not break. I would like to see this plugin be compatible, though also I would like to see a way for the new `gatsby-image-plugin` to deal with placeholders for each image tile which would load quicker before the image tiles load, this would be especially helpful for slow web connections. I could not find a way to do this before with `gatsby-image`, unless I missed something? Do you believe it's possible to bring about this feature request? Thanks 😊

**Comment by Qkessler** [comment]
Hi @linoxyn ! I have been able to work with Gatsby v3 and the leaflet components. I would also appreciate the v3 support added in order to lose the warnings developing with Gatsby v3.
Regards from Spain!
Enrique.

**Comment by fanczerni** [comment]
Hello! Is there any progress to make it compatible with Gatsby v3? :)

**Comment by dweirich** [comment]
@fanczerni Sorry no progress on this yet. Busy time of year for me. I will try to get an update out ASAP.

**Comment by pirtlj** [comment]
Would love to use this in Gatsby v3

**Comment by AlyonaTiki** [comment]
Can't wait for Gatsby 3 support, thank you!

**Comment by ekarmazin** [comment]
Yeah gatsby v3 would be amazing, thanks!

**Comment by Vacilando** [comment]
The plugin does not work with Gatsby 3 (no map), so an update would really be greatly appreciated, thank you!

**Comment by dweirich** [comment]
I've tested the package on a new Gatsby v3 build and it works. The package.json has been updated to reflect this. Sorry @linoxyn, the request for that image feature is outside of the scope for this project.
