### ISSUE TITLE
warning when using gatsby v4

### ISSUE THREAD

**Issue by barbalex** [dweirich/gatsby-plugin-react-leaflet#25]
```
warn Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 4.0.2 - It requires gatsby@^2.0.0 || ^3.0.0
```

I think it would be enough to add v4 to the peer dependencies as mentioned in the upgrade-docs of gatsby (https://v4.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#for-plugin-maintainers).

Would you accept a pull request?

**Comment by Jarek-Ch** [comment]
Workaround: add the plugin as a local plugin and change its package.json

**Comment by Vacilando** [comment]
Same problem:

> Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 4.2.0 - It requires gatsby@^2.0.0 || ^3.0.0

@dweirich: indeed it seems it should be enough to add v4 to the peer dependencies.
