### ISSUE TITLE
bump react-leaflet version to react-leaflet@"^4.0.0"

### ISSUE THREAD

**Issue by AlexCherrypi** [dweirich/gatsby-plugin-react-leaflet#30]
I would very much appreciate if the react-leaflet version could be bumped to react-leaflet@"^4.0.0"

**Comment by sabahossein** [comment]
@dweirich We would appreciate react-leaflet@"^4.0.0"

**Comment by Vacilando** [comment]
Much needed here as well, please support react-leaflet v4.

**Comment by dweirich** [comment]
A new update has been pushed to take care of this.
