### ISSUE TITLE
Invalid integrity for leaflet.css 1.3.4

### ISSUE THREAD

**Issue by hlouw** [dweirich/gatsby-plugin-react-leaflet#4]
Version 2.0.2 of the plugin links to `https://unpkg.com/leaflet@1.3.4/dist/leaflet.css`, but the integrity digest is for leaflet 1.3.3, resulting in error:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://unpkg.com/leaflet@1.3.4/dist/leaflet.css' with computed SHA-256 integrity 'YR4HrDE479EpYZgeTkQfgVJq08+277UXxMLbi/YP69o='. The resource has been blocked.
```

**Comment by dweirich** [comment]
Hi @hlouw I've pushed an update to fix this. Thanks for letting me know!

**Comment by kitchWWW** [comment]
Hello! I've run into the same issue all of a sudden this evening:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://unpkg.com/leaflet@1.3.4/dist/leaflet.css' with computed SHA-256 integrity 'OQnI66G0oU8IBjcY/aRkEaL0txBf2tcVHKV4eGkqAxk='. The resource has been blocked.
```
Any chance this can be fixed by a similar update?

**Comment by dweirich** [comment]
@kitchWWW Which version of the package are you using? The most recent version should be loading 1.5.1.
