### ISSUE TITLE
WebpackError: TypeError: htmlComponentRenderer.default is not a function

### ISSUE THREAD

**Issue by ian-s-mcb** [dweirich/gatsby-plugin-react-leaflet#6]
I can't get your README example code to run using `gatsby build`.

I get a
> error Building static HTML failed for path "/404/"
>  WebpackError: TypeError: htmlComponentRenderer.default is not a function
>
>  - bootstrap:24 Promise
>    lib/webpack/bootstrap:24:1
>
>  - bootstrap:68 new Promise
>    lib/webpack/bootstrap:68:1
>
>  - bootstrap:5 tryCatcher
>    lib/webpack/bootstrap:5:1
>
>  - bootstrap:50 MappingPromiseArray._promiseFulfilled
>    lib/webpack/bootstrap:50:1
>
>  - bootstrap:67 MappingPromiseArray.init
>    lib/webpack/bootstrap:67:1
>
>  - bootstrap:19 MappingPromiseArray._asyncInit
>    lib/webpack/bootstrap:19:1

![screenshot-gatsby_leaflet_build_error_2019-05-13](https://user-images.githubusercontent.com/2540024/57667660-633c7800-75d2-11e9-9d6e-d803ea52e53e.png)

### Package versions
```bash
$ yarn list gatsby gatsby-plugin-react-leaflet leaflet react-leaflet
yarn list v1.15.2
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ gatsby-plugin-react-leaflet@2.0.4
├─ gatsby@2.4.3
├─ leaflet@1.5.1
└─ react-leaflet@2.3.0
```

**Comment by ian-s-mcb** [comment]
The Gatsby / Leaflet code I used to produce this error is here: https://gitlab.com/ian-s-mcb/gatsby-leaflet-bug/blob/master/src/components/MyMap.js

**Comment by dweirich** [comment]
Thanks for catching that @ian-s-mcb. I've pushed a fix for this.

**Comment by ian-s-mcb** [comment]
Your fix didn't work work all the way. I upgraded my plugin version to `2.0.7` and now I have a window not defined error on build. I opened another issue: #9
