### ISSUE TITLE
fetch leaflet.css resulted in a network error response

### ISSUE THREAD

**Issue by kevbite** [dweirich/gatsby-plugin-react-leaflet#7]
I keep getting the following error when the page in loading and using the `gatsby-plugin-react-leaflet` plugin:
> The FetchEvent for "https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" resulted in a network error response: an "opaque" response was used for a request whose type is not no-cors
![image](https://user-images.githubusercontent.com/5544715/57986447-037c1c00-7a6d-11e9-8da4-af9744de977f.png)

I'm not really sure what it really means but it stops the content from being loaded, a bit of googling and it ended me up at this StackOverflow post - https://stackoverflow.com/questions/36292537/what-is-an-opaque-response-and-what-purpose-does-it-serve

To note I've also got the `gatsby-plugin-offline` plugin installed, so I'm guessing the leaflet.css is being served from the service worker?

I'm totally happy to help but no idea how to solve it. 

Thanks

**Comment by dweirich** [comment]
Hi @kevbite 

I've added an option that will hopefully help you resolve this. You can now configure the plugin with `linkStyles: false` to turn off loading the stylesheet from the CDN.

You should be able to import the css using something like `import 'leaflet/dist/leaflet.css'` but you will have to use one of the workarounds for loading the default icons if you don't have your own.

**Comment by kevbite** [comment]
Ok perfect, I'll try it out! Thanks!
