### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ian-s-mcb** [dweirich/gatsby-plugin-react-leaflet#9]
## Bug screenshot
![screenshot-gatsby_leaflet_bug_2019-05-24](https://user-images.githubusercontent.com/2540024/58340312-89a3b400-7e19-11e9-9101-ac09643b09b9.png)

## Plugin version
```bash
$ yarn list gatsby-plugin-react-leaflet
yarn list v1.15.2
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ gatsby-plugin-react-leaflet@2.0.7
Done in 0.70s.
```

## Code to reproduce bug:
```bash
git clone https://gitlab.com/ian-s-mcb/gatsby-leaflet-bug-2.git
cd  gatsby-leaflet-bug-2
git checkout -b broken ed18e68
yarn build
```

## Workaround:
* Use node `require()` instead of `import` for `react-leaflet` library
* Example code: `git checkout -b workaround 68e8359`

**Comment by ian-s-mcb** [comment]
It's probably worth pointing that this bug occurs upstream (https://github.com/PaulLeCam/react-leaflet/issues/495) and the maintainers have chosen not to support Server Side Rendering (SSR).

**Comment by dweirich** [comment]
@ian-s-mcb try updating to the latest version, this should work now. The package takes care of the SSR by not loading the libraries during the rendering.

**Comment by ian-s-mcb** [comment]
@dweirich That fixed it. Excellent. Thanks!
